### ISSUE TITLE
the error about readme

### ISSUE THREAD

**Issue by TingziGITHUB** [eurecom-asp/sasv-joint-optimisation#1]
![image](https://user-images.githubusercontent.com/114652588/227864577-d391d007-335f-4f41-b0a4-e7758499c5e5.png)
the command should be python main.py --config ./configs/ResNetSE34V2_AASIST_OC.conf instead of `python main.py --config ./config/ResNetSE34V2_AASIST_OC.conf`

**Comment by GeWanying** [comment]
Hi,

Thanks, you are right. I just changed it.

Have a good day.
